---

# Variables for sshd configuration
ssh_port:               "8383"
local_user:             "artembaidikov"
#path_to_inventory:      "/Users/artembaidikov/prparation_ubuntu/preperation_ubuntu_role/inventory/crt_droplet"

# Variables for fail2ban configuration
path_for_logs:          "/var/log/auth.log"
max_trys:               "3"
ban_time:               "180"
ignore_ip:              
  - 127.0.0.1
  - 217.77.221.128
find_time:              "600"

# Variables for configuration docker iptables 
install_docker:         ""
conf_docker:            ""
docker_vars: 
    - { in_interface: "docker0" }
    - { chain: "POSTROUTING", source: "172.17.0.0/16", table: "nat", jump: "MASQUERADE" }
    - { ctstate: "RELATED,ESTABLISHED", out_interface: "docker0" }
    - { in_interface: "docker0", out_interface: "!docker0" }
    - { in_interface: "docker0", out_interface: "docker0" }
    - { jump: "DROP", comment: "Custom DROP rule" }


